# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [22]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3,4])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,], [3,4]])


# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
a1,a2,a3

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [ ]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape , a1.ndim, a1.dtype, a1.size

In [ ]:
# Attributes of 2-dimensional array
a2.shape , a2.ndim, a2.dtype, a2.size

In [ ]:
# Attributes of 3-dimensional array
a3.shape , a3.ndim, a3.dtype, a3.size

In [ ]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
mat3 = pd.DataFrame(a3)
mat3

In [ ]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

In [ ]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

In [ ]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, size=(7,2))
random_array

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_float = np.random.random((3,5))
random_array_float

In [ ]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_seed = np.random.randint(0,10, size=(4,6))
random_seed

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_saved = np.random.randint(0,10, size=(3, 7))


# Find the unique numbers in the array you just created
np.unique(random_saved)

In [ ]:
random_saved

In [ ]:
# Find the 0'th index of the latest array you created
random_saved[0]

In [ ]:
# Get the first 2 rows of latest array you created
random_saved[:2]

In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
random_saved[:2, :2]

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_ranged = np.random.randint(0, 10, size=(3,5))
ones = np.ones((3,5))

In [ ]:
# Add the two arrays together
random_ranged + ones

In [ ]:
# Create another array of ones of shape (5, 3)
onesTwo = np.ones((5,3))

In [ ]:
# Try add the array of ones and the other most recent array together
ones + onesTwo

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
# Create another array of ones of shape (3, 5)
onesThree = np.ones((3,5))

In [ ]:
# Subtract the new array of ones from the other most recent array
ones - onesThree

In [ ]:
# Multiply the ones array with the latest array
ones * random_ranged

In [ ]:
# Take the latest array to the power of 2 using '**'
random_ranged ** 2

In [ ]:
# Do the same thing with np.square()
np.square(random_ranged)

In [ ]:
# Find the mean of the latest array using np.mean()
np.mean(random_ranged)

In [ ]:
# Find the maximum of the latest array using np.max()
np.max(random_ranged)

In [ ]:
# Find the minimum of the latest array using np.min()
np.min(random_ranged)

In [ ]:
# Find the standard deviation of the latest array
np.std(random_ranged)

In [ ]:
# Find the variance of the latest array
np.var(random_ranged)

In [ ]:
# Reshape the latest array to (3, 5, 1)
random_ranged_reshaped = random_ranged.reshape(3,5,1)

In [ ]:
# Transpose the latest array
random_ranged_reshaped.T

What does the transpose do?

In [23]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_random = np.random.randint(0,10, size=(3,3))
array_random2 = np.random.randint(0,10, size=(3,2))

In [24]:
# Perform a dot product on the two newest arrays you created
np.dot(array_random, array_random2)

array([[ 48,  33],
       [112, 127],
       [ 76,  70]])

In [25]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_random = np.random.randint(0,10, size=(4, 3))
array_random2 = np.random.randint(0,10, size=(4, 3))


In [26]:
# Perform a dot product on the two newest arrays you created
np.dot(array_random, array_random2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [27]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(array_random, array_random2.T)

array([[ 72,  50, 201, 184],
       [ 68,  24, 102,  96],
       [ 49,  16, 114, 106],
       [ 53,  22, 123, 114]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [30]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a1 = np.random.randint(0,10, size=(4,4))
a2 = np.random.randint(0,10, size=(4,4))

In [31]:
# Compare the two arrays with '>'
a1 > a2

array([[ True,  True, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [False,  True,  True, False]])

What happens when you compare the arrays with `>`?

In [32]:
# Compare the two arrays with '>='
a1 >= a2

array([[ True,  True, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [False,  True,  True, False]])

In [33]:
# Find which elements of the first array are greater than 7
a1 > 7

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [ True,  True,  True, False]])

In [34]:
# Which parts of each array are equal? (try using '==')
a1 == a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [36]:
# Sort one of the arrays you just created in ascending order
a1.sort()
a1

array([[0, 2, 5, 7],
       [0, 2, 2, 4],
       [4, 6, 6, 9],
       [2, 8, 9, 9]])

In [38]:
# Sort the indexes of one of the arrays you just created
np.argsort(a2)

array([[1, 2, 3, 0],
       [3, 0, 1, 2],
       [3, 1, 2, 0],
       [2, 3, 1, 0]], dtype=int64)

In [39]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a1)

11

In [40]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a1)

0

In [41]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a1, axis=1)

array([3, 3, 3, 2], dtype=int64)

In [42]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(a1, axis=0)

array([2, 3, 3, 2], dtype=int64)

In [43]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)


array([[-1.48242425, -0.22884752,  0.96264129, -0.20969244, -0.77404293],
       [-0.35977815,  0.72408325, -0.25576464,  0.8499212 , -1.31132423],
       [-0.87030495, -0.50664322, -1.30995069,  2.94366342, -1.0962658 ]])

In [46]:
# Create an array with 10 evenly spaced numbers between 1 and 100
x = np.linspace(1, 100, 10)
x[:4]

array([ 1., 12., 23., 34.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.